services:
  streamlit-app:
    image: "streamlit-app:latest"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8501
    ports:
      - 8501:8501
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always
